permalink: /:year/:month/:day/:title 

pygments: true

title : Gowanda Theater
tagline: 
author :
  name : Nicholas Gunner
  email : gunnernr@gmail.com
  github : ngunner
  twitter : canopymaps
  web : http://www.nicholasgunner.com

production_url : http://nicholasgunner.github.io/gowanda-theater


baseurl : http://nicholasgunner.github.io/gowanda-theater

 
comments :
  provider : disqus
  disqus :
    short_name : 
        
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-46443510-2'
  
authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: New Media Manager at SUNY Fredonia
    gravatar: http://www.gravatar.com/avatar/a85d870dce3cc177b6b0016a1ef4c200.png
    email: gunner@fredonia.edu
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
   

  
timezone : America/New_York
